#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'

	delete system.ntp.server
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.tencent.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='time.ustc.edu.cn'
EOF
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

#################### wireless
# 5G信道
uci set wireless.@wifi-device[0].channel='36'
# 5G频宽
uci set wireless.@wifi-device[0].htmode='HE80'
# 5G MIMO
uci set wireless.@wifi-device[0].mu_beamformer='1'
# 5G地区
uci set wireless.@wifi-device[0].country='CN'
# 5G加密算法
uci set wireless.@wifi-iface[0].encryption='psk2'
# 5G SSID
uci set wireless.@wifi-iface[0].ssid='FK20100010_5G'
# 5G 密码
uci set wireless.@wifi-iface[0].key='qwerqwe123@'

# 2.4G信道
uci set wireless.@wifi-device[1].channel='11'
# 2.4G频宽
uci set wireless.@wifi-device[1].htmode='HE20'
# 2.4G MIMO
uci set wireless.@wifi-device[1].mu_beamformer='1'
# 2.4G地区
uci set wireless.@wifi-device[1].country='CN'
# 2.4G加密算法
uci set wireless.@wifi-iface[1].encryption='psk2'
# 2.4G SSID
uci set wireless.@wifi-iface[1].ssid='FK20100010'
# 2.4G 密码
uci set wireless.@wifi-iface[1].key='qwerqwe123@'
#默认打开WIFI
uci set wireless.@wifi-device[0].disabled=0
uci set wireless.@wifi-device[1].disabled=0
# 提交更改
uci commit wireless
#lan ip
uci set network.lan.ipaddr=192.168.10.1
uci commit network

#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/share/luci/menu.d/luci-app-samba4.json
sed -i '/passwall/d' /etc/opkg/distfeeds.conf

sed -i 's~root::0:0:99999:7:::~root:$5$wWuQ48EcwP8fJ2Xq$GGvJHda1R2bYVNWbsG4lGS/Yn/kUxWDDLfYac9p9PI.:20019:0:99999:7:::~g' /etc/shadow
sed -i 's~root:::0:99999:7:::~root:$5$wWuQ48EcwP8fJ2Xq$GGvJHda1R2bYVNWbsG4lGS/Yn/kUxWDDLfYac9p9PI.:20019:0:99999:7:::~g' /etc/shadow

sed -i '/check_signature/d' /etc/opkg.conf

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh


exit 0
